In [1]:
l = [1, 3, 77, 2938, -55]

In [2]:
l

[1, 3, 77, 2938, -55]

In [3]:
import numpy as np

In [5]:
a = np.array(l)
a

array([   1,    3,   77, 2938,  -55])

In [8]:
b = np.array(['25', 'ai ai ai','hahaha', 55, True ])
b
#note that it coverted to strings, because arrays can't have different types 

array(['25', 'ai ai ai', 'hahaha', '55', 'True'], dtype='<U21')

In [10]:
#using arrays is good because we can use function/methods

l.pop()

-55

In [11]:
a.mean()

592.8

In [12]:
#slicing arrays
#unlike using lists, when we slice an array we DON'T make a copy of it, we create a view
#if you change values inside the array it will be changed on the original
#but is possible to make a copy with the .copy method

a[0:1]

array([1])

In [14]:
a [:] = 111
a

array([111, 111, 111, 111, 111])

In [17]:
c = a.copy()
c

array([111, 111, 111, 111, 111])

In [19]:
c [0:4:2] = 33, 45
c

array([ 33, 111,  45, 111, 111])